package days;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

public class Day5_BinaryBoarding {

	public static void main(String[] args) {
		System.out.println("answer A: " + runA(getTextInput()));
		System.out.println("answer B: " + runB(getTextInput()));
	}

	public static int runA(String input) {
		return Arrays.stream(input.split("\n"))
				.map(Day5_BinaryBoarding::getSeatNum)
				.mapToInt(i -> i)
				.max().getAsInt();

	}

	public static int runB(String input) {
		List<Integer> allSeatNums = Arrays.stream(input.split("\n"))
				.map(Day5_BinaryBoarding::getSeatNum)
				.sorted()
				.collect(Collectors.toList());

		int firstSeat = allSeatNums.get(0);

		return IntStream.range(0, allSeatNums.size())
				.filter(i -> allSeatNums.get(i) - i != firstSeat)
				.findFirst()
				.getAsInt() + firstSeat;
	}

	private static int getSeatNum(String boardingpass) {
		int row = 0;
//		FBFBBFFRLR
		char[] chars = boardingpass.toCharArray();
		row += chars[0] == 'B' ? 64 : 0;
		row += chars[1] == 'B' ? 32 : 0;
		row += chars[2] == 'B' ? 16 : 0;
		row += chars[3] == 'B' ? 8 : 0;
		row += chars[4] == 'B' ? 4 : 0;
		row += chars[5] == 'B' ? 2 : 0;
		row += chars[6] == 'B' ? 1 : 0;

		int column = 0;

		column += chars[7] == 'R' ? 4 : 0;
		column += chars[8] == 'R' ? 2 : 0;
		column += chars[9] == 'R' ? 1 : 0;

		return row * 8 + column;
	}

	private static String getTextInput() {
		return "FFBFFBBLRL\n" +
				"FBFBBFBLRR\n" +
				"FBFFBBBRLL\n" +
				"FFBBFBFRRR\n" +
				"BFBBBBFLRR\n" +
				"BBFBBBFRRL\n" +
				"BFBBBBBLLR\n" +
				"FBFFBFBRRR\n" +
				"BBFFBBBLRL\n" +
				"BBBFFFFLLR\n" +
				"FFFFBFFRLL\n" +
				"FFBFFFFRLL\n" +
				"FFFBFBBLRR\n" +
				"BFBFBBBRLR\n" +
				"FBBFBBBLRR\n" +
				"BBFFFFBRRR\n" +
				"FBBFFFBRRR\n" +
				"BFFFBFFLLR\n" +
				"FBBBBFFLRL\n" +
				"BFBFFFBRRL\n" +
				"FFBFBBFRRL\n" +
				"BBFBFFFRRR\n" +
				"FFBFFBFLRR\n" +
				"FFBFFBBLLR\n" +
				"FBFBFFFLRR\n" +
				"FFFBFFFRRL\n" +
				"FFFFFBFRRL\n" +
				"BBBFFFFRLL\n" +
				"FBBFBFFLLL\n" +
				"FBBBBFBLRL\n" +
				"BBBFBBFRRR\n" +
				"BBBFBFBLLL\n" +
				"FBBFFBBLLL\n" +
				"FBBBFBFLRL\n" +
				"FBBBFBFRLL\n" +
				"BFFFFFFLRR\n" +
				"FFFFBBBRRR\n" +
				"FBFBBBFLLL\n" +
				"FBFBFBFRLL\n" +
				"FBBBFBFLLR\n" +
				"FBBFFFFLRR\n" +
				"FFBBBBFRRL\n" +
				"FFBBBBFRLR\n" +
				"FBFBBBBLRL\n" +
				"BFFFFFFRRL\n" +
				"FBBBFFBLLL\n" +
				"FBFFFFFRLL\n" +
				"BFFFFBFRRL\n" +
				"FFBBBFBLRL\n" +
				"FBFFBFFRLR\n" +
				"FBFFBBFLRL\n" +
				"BFFFBFBRLL\n" +
				"BFFFFFFLLL\n" +
				"FFFBBFBLRR\n" +
				"FBFBFBBRLR\n" +
				"BBFFBFFLRR\n" +
				"BBFFFBBLRR\n" +
				"BFBFBBFRLR\n" +
				"FBBFBBBLLR\n" +
				"FFFFBBFLLL\n" +
				"BBFBBBFLRL\n" +
				"BFFBBBFRLR\n" +
				"FBFFFFBLLR\n" +
				"FFFFBFFLRL\n" +
				"BBFBFBFLRR\n" +
				"BFFBFFBLLR\n" +
				"BBFBBBFLRR\n" +
				"FFFFBBFRLR\n" +
				"FBBFFBBLRL\n" +
				"FBBBBBBRLL\n" +
				"FBBFBFBRLR\n" +
				"FFBBFBFRLL\n" +
				"FFBFBFFLRR\n" +
				"BFFBBBBLLR\n" +
				"FBFBFBFRRL\n" +
				"BBBFBBFLLL\n" +
				"FFBBFFBLRR\n" +
				"BBFBBFBLRR\n" +
				"BFFFBBBLLL\n" +
				"BBBFFBFRRL\n" +
				"FBBBFBFLLL\n" +
				"FBFBFBBRRL\n" +
				"BFBFFBBLLR\n" +
				"FFBFFBBRRR\n" +
				"BBFFFFFLLL\n" +
				"BFFBFFBLLL\n" +
				"BBBFBFFRRL\n" +
				"FBFFBFBRLR\n" +
				"BFFBBFFLRR\n" +
				"BFBFBBFLRR\n" +
				"FBBBBFBRLR\n" +
				"BFBBBBBRLL\n" +
				"BFBBBFBLRR\n" +
				"BFFFFFBLLR\n" +
				"BBBFFFBLRL\n" +
				"BFFFBFBLRL\n" +
				"BFFFBBBLRR\n" +
				"BBFBBBBRLL\n" +
				"FFBBFBFLLL\n" +
				"BFFBFBBRRL\n" +
				"BFFBBFBRRR\n" +
				"BBFBBBBRRR\n" +
				"FFBBBBBLLL\n" +
				"FBBBFFBLRL\n" +
				"FFBFFBFLRL\n" +
				"FFBBBBFRLL\n" +
				"FFFFBBFLRR\n" +
				"BBFFFFBRRL\n" +
				"BFFFFBBRRR\n" +
				"FFFBFBFRLR\n" +
				"FBBBBBFLRR\n" +
				"FFFFBBBRRL\n" +
				"BFBFBFBRRR\n" +
				"BFFBBBFRRR\n" +
				"FFFFFFBLLL\n" +
				"FFFBBFBLLL\n" +
				"FBFFFBFLRL\n" +
				"BFFFBBFLRR\n" +
				"FBBBBBFRLL\n" +
				"FBFFFFBRLL\n" +
				"FBFBBBFRLL\n" +
				"FFBFBBBLRL\n" +
				"BFBFBFFLLL\n" +
				"BBBFBFBLLR\n" +
				"FBBBBFFRRR\n" +
				"FBBFBFFRLR\n" +
				"FBFFBFFRRR\n" +
				"BFBFBFFLRR\n" +
				"BBFFFBFLRL\n" +
				"BBFFFBBRRL\n" +
				"BFFBBFFLLL\n" +
				"BFBBFFFRLL\n" +
				"FFFBFFBRLR\n" +
				"BBFBBFBLLR\n" +
				"BBBFFFFRLR\n" +
				"BFBBFBBRRR\n" +
				"FBBBFBFRRL\n" +
				"BBFBBBBLLR\n" +
				"BFFBBBBRRR\n" +
				"FFFFFBFLLL\n" +
				"BBBFBFFLRL\n" +
				"FBFFFFBLLL\n" +
				"BFFBBBFRRL\n" +
				"FBFBBFBLRL\n" +
				"FFBFBBBRLR\n" +
				"FFFBBBBLLL\n" +
				"BBFBBFFRLL\n" +
				"BBFBFBBRLL\n" +
				"BBFBFBBRRL\n" +
				"BFBBBFBRLR\n" +
				"FBFBFFFRLL\n" +
				"BFFFBFFRRL\n" +
				"BFFFFBFLRR\n" +
				"BFBBFFBRRL\n" +
				"BBFFBBFRRL\n" +
				"BBBFFFFLLL\n" +
				"FBFFBFBRRL\n" +
				"FFFBBFBRRL\n" +
				"FBFFBFFLLL\n" +
				"FFFBFBBLRL\n" +
				"BBFFBFBLLL\n" +
				"FFBBBFBLLL\n" +
				"BFBBBFFLRL\n" +
				"BFBFBBBRRL\n" +
				"FFBBBBFLRR\n" +
				"FBBFFBFRRR\n" +
				"FFBFBFBRLL\n" +
				"BFBBFFBLLR\n" +
				"BFFBFBFRRL\n" +
				"FBFFFFFLRR\n" +
				"FBFBBBBRLR\n" +
				"BFFFFFBLRR\n" +
				"BBFBFFFRLL\n" +
				"FFBFBBFLRR\n" +
				"BBFFFFFRLL\n" +
				"BFFBBFBRLR\n" +
				"FFBBFBBRLR\n" +
				"BFBBFFFLRL\n" +
				"FFFFFFFRRL\n" +
				"FFBBBBBLRL\n" +
				"FFFBBBBLLR\n" +
				"FFFBBFFLLR\n" +
				"FFFBFFFRLL\n" +
				"BFBFFBBRRL\n" +
				"BBFBBFFRRL\n" +
				"FFBFFBBRRL\n" +
				"FFBFFFFRRL\n" +
				"FFFBFFBRLL\n" +
				"FBFBFFFRLR\n" +
				"FFFBFBFRRR\n" +
				"BFBBBBFRRR\n" +
				"BBBFBFFRLL\n" +
				"FBBFFFFRLR\n" +
				"BFFBBBBLRR\n" +
				"FFBBBBBRLL\n" +
				"FFBBFBFLRL\n" +
				"BBBFFBBRLL\n" +
				"BBFBBBFRLL\n" +
				"BFBBFBFRRR\n" +
				"FBFBBFBRRL\n" +
				"FBBFBBBRRL\n" +
				"FFBFFBBRLR\n" +
				"FFFFFBFLRL\n" +
				"FBFBFFFLLL\n" +
				"FBFFBBFRLL\n" +
				"FBBBFFFRRR\n" +
				"BFFBFBBRLL\n" +
				"BFBFFFFRLL\n" +
				"BBFFFBBLLR\n" +
				"FFBBFBBLLL\n" +
				"BBBFFFBLLR\n" +
				"FFFBBBBRLL\n" +
				"BFBBBBFRLL\n" +
				"BFBBBFFLRR\n" +
				"BFFFFFFLLR\n" +
				"BFBBBBFLLL\n" +
				"FBBBFFFLRL\n" +
				"FBBBBFBLLL\n" +
				"BFFFBBFRRL\n" +
				"FBBBBFFRLR\n" +
				"BBFBFBFRLR\n" +
				"BFFBFBFLRR\n" +
				"BBFBFFBRRL\n" +
				"FFFFFFBRRL\n" +
				"FBFBFBBLRL\n" +
				"BFBFFBBLRR\n" +
				"FFBBFBFRRL\n" +
				"FBFFFBFLLR\n" +
				"FBBBBBBRRR\n" +
				"BBBFBFFLRR\n" +
				"FBBFBBBRLL\n" +
				"FFBFFBBLLL\n" +
				"BBFFBFBRRR\n" +
				"BFFBBBFLRR\n" +
				"FFFBFFFLLR\n" +
				"FBBFBFFRLL\n" +
				"BBFFFFBLLL\n" +
				"BFBFBFFLRL\n" +
				"BBFBBFBRRR\n" +
				"BBFFFBBRLL\n" +
				"BFFBBFBRLL\n" +
				"FFFFFFBRLL\n" +
				"BFFBFFBRLL\n" +
				"BFFBBFBLRR\n" +
				"BFBBBBFLRL\n" +
				"BBFFFFBLRL\n" +
				"FFFBBBFLRR\n" +
				"BFBBFBBLRL\n" +
				"FBBBFBBRLL\n" +
				"BBFBBFBRLR\n" +
				"BFFBBFBLLL\n" +
				"FBBBBBFRRL\n" +
				"BFFBBBFLRL\n" +
				"FFFBBFFRLR\n" +
				"FBBFFFFRLL\n" +
				"BFFFFBFRLL\n" +
				"FFBBBFBRLL\n" +
				"FFFBFFFRLR\n" +
				"BFBBFFFRRL\n" +
				"BFBFFBBRRR\n" +
				"FFBBFBFLRR\n" +
				"FFFBFFBLLR\n" +
				"BBFBBFFRLR\n" +
				"BFFBBFFRRL\n" +
				"FBBFFFFLRL\n" +
				"FBFBBFFRLL\n" +
				"BBFBFBBLLR\n" +
				"FFFFFBBLRR\n" +
				"BFBBBFFLLR\n" +
				"BFBFFBFLRR\n" +
				"BFBBFBFRRL\n" +
				"FBBFBBFRLR\n" +
				"BBFBBBFLLR\n" +
				"BFFFBBBRLR\n" +
				"FBFFBFFRLL\n" +
				"BFBBFFFRLR\n" +
				"BBFFBBFRLR\n" +
				"BBFBFFBLRL\n" +
				"BBBFBFBRLL\n" +
				"FFFFBFFLRR\n" +
				"BFBFBBBLLL\n" +
				"BFFFFBFLRL\n" +
				"BFBBBFBRLL\n" +
				"FFFBFFBLRR\n" +
				"FFFBBFBRLR\n" +
				"BBFFFBBLLL\n" +
				"FFFBBBBRRL\n" +
				"FFBFBFFRLR\n" +
				"BBBFFBBLRL\n" +
				"FFBFFBFLLL\n" +
				"FFFBFBBLLR\n" +
				"FFBFFFFLRL\n" +
				"FFBBFFFLLL\n" +
				"FBFFFBBRRL\n" +
				"BFFFFBBLLR\n" +
				"BFBFFFFRRR\n" +
				"FBFBFBBRLL\n" +
				"BFBBBFFRLL\n" +
				"BFFBBFFLRL\n" +
				"FFBBFFBLLL\n" +
				"FBBBBFBRRL\n" +
				"BBFFFBFRRL\n" +
				"FFFBBFBLRL\n" +
				"BBBFFFBRLR\n" +
				"BFBBFFFRRR\n" +
				"FFBFBBBRRR\n" +
				"BFFFBFBRRL\n" +
				"FBBFFBFRLL\n" +
				"BBBFFBBLLL\n" +
				"FBBFBBBRLR\n" +
				"BBBFBBFLRR\n" +
				"BBFFFFBRLR\n" +
				"BFFFBFBRLR\n" +
				"FBBBFBFRLR\n" +
				"BFBBFFFLLL\n" +
				"FBBBBBBRRL\n" +
				"BBFFBBBRLR\n" +
				"BFFFFFFRRR\n" +
				"BBFFFBBRLR\n" +
				"FBFBBFBLLL\n" +
				"BFBFBBBLLR\n" +
				"FBBBFBBLRL\n" +
				"FFBFFFBRRR\n" +
				"BFFFFBBRLL\n" +
				"BBFBBFFLRR\n" +
				"FBBBFBFLRR\n" +
				"BFFBFFFLLR\n" +
				"BBBFFFFLRR\n" +
				"BFFBFBFRRR\n" +
				"FFFFFFBRRR\n" +
				"BFBFFFFLRR\n" +
				"BFFFBBBLRL\n" +
				"FBBBFFBLRR\n" +
				"FFFFBFFLLL\n" +
				"FFBBFFFLLR\n" +
				"BFBBFFBRLR\n" +
				"FBFFBBFLLL\n" +
				"FFFBBBFRLL\n" +
				"BFBBFFBLRR\n" +
				"BFFBFFBRRR\n" +
				"FBFBBFFLRR\n" +
				"BFFBFBFLLR\n" +
				"FBFFFFBLRR\n" +
				"FBFFFBBLRR\n" +
				"BFBFFBFRRL\n" +
				"FFBFBFBLRL\n" +
				"FBFBBBBRRL\n" +
				"BBFFFFFRLR\n" +
				"FFBFFBFRRL\n" +
				"FFBBFFBRRR\n" +
				"BBFFBFFRRL\n" +
				"FFFFFBBRLR\n" +
				"BFBBFFFLLR\n" +
				"FFFBBFFLRR\n" +
				"BFFBFBBRLR\n" +
				"FBFFBFBLLL\n" +
				"FFBBFBFLLR\n" +
				"FFBBFFFRLR\n" +
				"BFBFFFFRRL\n" +
				"FBBFBBBRRR\n" +
				"BFFFFBFRRR\n" +
				"BFBFBFBLLR\n" +
				"BBBFBFFRLR\n" +
				"BFFFBFBRRR\n" +
				"FBFBFFBLRR\n" +
				"BBFFBBFRLL\n" +
				"BFBFBBFLRL\n" +
				"BFBFFFFLRL\n" +
				"BBBFBFBRLR\n" +
				"FFBBBBFLLL\n" +
				"FBBBFFBRLL\n" +
				"FFBFFFBRLR\n" +
				"FFBBBFFRRL\n" +
				"FFBBBBBLLR\n" +
				"FFFFBFBLRL\n" +
				"FFFBFFFLRL\n" +
				"FBBBBBBLLR\n" +
				"BFFFBBFLRL\n" +
				"FBBFBFFLRL\n" +
				"FFBFFBFLLR\n" +
				"FFBBBBBRRR\n" +
				"FFFBFBFRRL\n" +
				"BFFBFFFRLR\n" +
				"FFBFFBBLRR\n" +
				"BBFFFFFLRR\n" +
				"BBBFBBFRRL\n" +
				"BBFFFBFRLL\n" +
				"FBFBFBBLRR\n" +
				"BBFFFBBRRR\n" +
				"BBBFBFBLRL\n" +
				"FBBBFFFRLR\n" +
				"BFFFBBFLLL\n" +
				"FBBBBFFLRR\n" +
				"FFBBFFBRLR\n" +
				"FFBFFFFRRR\n" +
				"FBFBFBFLRR\n" +
				"BBBFFFFRRR\n" +
				"FBFFFBFRRL\n" +
				"FFBFFFFLLL\n" +
				"BBFBBBBRRL\n" +
				"FBFFBBFLRR\n" +
				"FBFBBFFRRR\n" +
				"BFFFBBBLLR\n" +
				"FFBBBFFLRR\n" +
				"BFFFFBBRRL\n" +
				"FFBFFFFLRR\n" +
				"BFFBFBFLRL\n" +
				"BFFBBBBRLR\n" +
				"BFFBFBBLLL\n" +
				"BFBBBBBRRR\n" +
				"FFBBFBBLRL\n" +
				"BFBFFBFLRL\n" +
				"BBFBBBFRLR\n" +
				"FBBFBBFRLL\n" +
				"BFBFFBBRLL\n" +
				"FBFBBBBRLL\n" +
				"FFBBFBBLRR\n" +
				"BFBFFBBLLL\n" +
				"FFBFFFBLLR\n" +
				"BFBBBFBRRL\n" +
				"BBFFFBFLRR\n" +
				"BBFFBBFLRL\n" +
				"FBBFBFBLLR\n" +
				"BBBFBBFRLR\n" +
				"FBBBBBFRLR\n" +
				"BFBBFBFLLL\n" +
				"FBFFFFBLRL\n" +
				"FBBFFBBLLR\n" +
				"FBBFFBBRLR\n" +
				"FFFFBFBRRR\n" +
				"FBBFFBFLRL\n" +
				"FBFBBBBRRR\n" +
				"FBBFFFFRRL\n" +
				"FFFBBBBLRL\n" +
				"BFFBFBFRLL\n" +
				"FFBFBFFRRR\n" +
				"FFFBBFFRRR\n" +
				"BBFFBBBLRR\n" +
				"FFBFFFBLRR\n" +
				"FFBBFBBRLL\n" +
				"FFBBFFFRLL\n" +
				"FBBBFBBLLL\n" +
				"BBFFBFFRLL\n" +
				"FBBFBFBLRR\n" +
				"BBBFFFBLLL\n" +
				"FBFBFBFLRL\n" +
				"BFFBBFBLLR\n" +
				"BFBFBBFLLR\n" +
				"BFBBBFFRRR\n" +
				"FBFFFBFRRR\n" +
				"FFBFFFBRRL\n" +
				"BBFFBBFRRR\n" +
				"BFBBFBBLLL\n" +
				"FFFFFBBRLL\n" +
				"FBFFBFFLRL\n" +
				"FFBFBFBLLR\n" +
				"FFBBBBFLLR\n" +
				"BFBFFBFRRR\n" +
				"BFFFFFBRRL\n" +
				"BFFFFBFLLR\n" +
				"FFFBBBFLLR\n" +
				"BFBFBFBLRR\n" +
				"FFFFBBFLLR\n" +
				"BBBFFBBRRR\n" +
				"FFBFBFBRRR\n" +
				"FBFBBBFLRR\n" +
				"BFFFFBBRLR\n" +
				"BFFBFFBRLR\n" +
				"BFBBFBBRRL\n" +
				"FFBBFBBRRR\n" +
				"FBBFBBFLRR\n" +
				"BBFFBBBRRL\n" +
				"FBBBBBBLRR\n" +
				"FFFBFFFRRR\n" +
				"FFFFBFBRRL\n" +
				"FBFFBFFLRR\n" +
				"BFFBFFFLRR\n" +
				"FFBFFBBRLL\n" +
				"FBFBBFFLLR\n" +
				"BFBFFBFRLR\n" +
				"BBFBFFFLRL\n" +
				"BFFFFFFLRL\n" +
				"FBFFFBFRLR\n" +
				"FBFBBFBLLR\n" +
				"FBBBBFFLLL\n" +
				"BFBFBBFLLL\n" +
				"BBFFFBFRLR\n" +
				"BFBBBBFLLR\n" +
				"FFFFBBBRLR\n" +
				"BFBFFBFLLR\n" +
				"BBBFBFFLLL\n" +
				"BFFFFFBRLL\n" +
				"FFBBFBBLLR\n" +
				"FBBBBFFRRL\n" +
				"FFBBFFBLRL\n" +
				"FBFBBBFLLR\n" +
				"FBFFBFBLRL\n" +
				"FBBBFFFLRR\n" +
				"FFBFBFFRRL\n" +
				"FBBBBBBRLR\n" +
				"FFFBBFBRLL\n" +
				"FBFBFFBRLR\n" +
				"BBBFBFBRRR\n" +
				"FBBBBBBLLL\n" +
				"FFFFBBBLLL\n" +
				"BBFBFBFLRL\n" +
				"BBFFFFFRRL\n" +
				"FBBBFFBRLR\n" +
				"FFFFBFFLLR\n" +
				"BFFBBFFRLL\n" +
				"FBFFBBFRRL\n" +
				"BFBFFFBRRR\n" +
				"FBFFBFFRRL\n" +
				"FFFFFBBLLR\n" +
				"BBFFFFBRLL\n" +
				"FFFBFBFLLL\n" +
				"BFBBFBFRLR\n" +
				"BFBFBBBLRR\n" +
				"BFFFBBBRRR\n" +
				"FFFFFFBLRL\n" +
				"FFFFFFBLRR\n" +
				"BFBFFBBRLR\n" +
				"BBBFFBFLLR\n" +
				"FBFFFBBLLL\n" +
				"BBBFFBFLLL\n" +
				"BBFFBBFLRR\n" +
				"BFFBFFFRRL\n" +
				"FFBFBBBRLL\n" +
				"FBBBBBFLLL\n" +
				"BBFBFFBRRR\n" +
				"BBFFFFFLRL\n" +
				"BFFBFBBLRL\n" +
				"BFBBBFFLLL\n" +
				"BFBFBFFRRR\n" +
				"FFBBFBBRRL\n" +
				"FBFBBFFLLL\n" +
				"BBFFBFFRRR\n" +
				"FBBFFFBRRL\n" +
				"BBBFBBFRLL\n" +
				"FFFFBBFRLL\n" +
				"BBBFFBBRRL\n" +
				"BBFBBBFRRR\n" +
				"FBBFFBBRRL\n" +
				"BFBBBBFRLR\n" +
				"BFBFBBFRLL\n" +
				"FFBFBFBLRR\n" +
				"BFFBFBBLLR\n" +
				"FBFBBBFRRR\n" +
				"FFFBBBBLRR\n" +
				"FBFFFBBRLL\n" +
				"BBFFFBFRRR\n" +
				"FBFFFFBRRL\n" +
				"FBBFFFBRLL\n" +
				"FBFFFFFLLL\n" +
				"FBBBBBFLRL\n" +
				"BBFFBFFLRL\n" +
				"BBBFBBFLLR\n" +
				"FBFFBFFLLR\n" +
				"FFBBFFFRRR\n" +
				"BFFFFFBRRR\n" +
				"FFBFBFBLLL\n" +
				"FFFFBFBRLL\n" +
				"BBFBFFBRLR\n" +
				"BBFFBFBRLL\n" +
				"FBBFFBFRLR\n" +
				"FBBBFFBRRL\n" +
				"FFFBBBBRRR\n" +
				"BBFFFFBLRR\n" +
				"FFBFBBFRRR\n" +
				"BFFFFFBLRL\n" +
				"FFBFBFBRRL\n" +
				"FFBBFBFRLR\n" +
				"FFBFBBBRRL\n" +
				"BFFFFBBLRL\n" +
				"FBBFBFBRRR\n" +
				"BFFFFFFRLR\n" +
				"FFFFBFFRLR\n" +
				"BFBFFBFRLL\n" +
				"BFFBBFFRRR\n" +
				"BFFBFFBLRR\n" +
				"FBFBFFFLLR\n" +
				"BFBFBFBRLL\n" +
				"BBFFFBFLLL\n" +
				"BFBFFFBRLL\n" +
				"BFBFBFFRLL\n" +
				"FBFBBBFLRL\n" +
				"FBFFFFFLRL\n" +
				"BBFBBFBRRL\n" +
				"FFBFFFBRLL\n" +
				"FBBFFFBLLR\n" +
				"FFBBBFFLRL\n" +
				"BFFBFBFRLR\n" +
				"FBFFFBBLLR\n" +
				"FFFBFFFLLL\n" +
				"FBBBBBFRRR\n" +
				"BFBFBFBLRL\n" +
				"BBBFFBFLRR\n" +
				"BBBFBBFLRL\n" +
				"BBFBFFFLLR\n" +
				"FBBFFFBLLL\n" +
				"BFBFFFBLRL\n" +
				"FBFBFBBRRR\n" +
				"FBBBFBBRRL\n" +
				"FFFFFFBRLR\n" +
				"FBBFBBFRRL\n" +
				"BBFBFBFLLL\n" +
				"BBFBBBBRLR\n" +
				"BFBBBBBLRL\n" +
				"FBBBBFBRLL\n" +
				"BFFBFFFLRL\n" +
				"BFBBBFFRRL\n" +
				"FFBBBFBLLR\n" +
				"FBFFBBBLLL\n" +
				"FFFFFFBLLR\n" +
				"FFFBFFBLRL\n" +
				"FFFBFFFLRR\n" +
				"FFBBFFFLRL\n" +
				"FBFBFFFRRR\n" +
				"FBFBFBBLLR\n" +
				"FFFFBBBLLR\n" +
				"FFBBBBBRLR\n" +
				"BFBBBBBLRR\n" +
				"BBFBFBFRLL\n" +
				"BFBFFFBLLL\n" +
				"FBBBFBFRRR\n" +
				"FBBFBBFLRL\n" +
				"FFFBBFFLRL\n" +
				"FFFBFBFLRL\n" +
				"FBFBBBBLRR\n" +
				"FFFBBFBRRR\n" +
				"FFFBBFFRLL\n" +
				"FFBBFFBLLR\n" +
				"FBBBBBFLLR\n" +
				"BFBFBFFRRL\n" +
				"BBFBBFBRLL\n" +
				"FBBBFFBRRR\n" +
				"FBFBBFBRLR\n" +
				"FBBFBBBLRL\n" +
				"BFFFFBFRLR\n" +
				"BBFBBBBLRR\n" +
				"BFFBBFFLLR\n" +
				"FBBFFFFLLL\n" +
				"FBFFFFBRLR\n" +
				"FFFFBBFRRL\n" +
				"BFFFBFFLLL\n" +
				"FFFFBBBLRR\n" +
				"FBFFBBBLRL\n" +
				"FFBFFFFRLR\n" +
				"BBBFFBFLRL\n" +
				"BFFBBBBLLL\n" +
				"FFFFFBBRRL\n" +
				"BFBBFFBLLL\n" +
				"BFBBFBFLRR\n" +
				"BFFBBBFLLL\n" +
				"FBFFFBFLLL\n" +
				"FBBFFFBLRL\n" +
				"FFBBBBFLRL\n" +
				"FBFFFBFRLL\n" +
				"FBBFFFBRLR\n" +
				"FBFBBFFLRL\n" +
				"FBBBBFBRRR\n" +
				"FBBBBFBLRR\n" +
				"BBFFBFBLLR\n" +
				"FFBFBBBLLL\n" +
				"FFFFFFFRRR\n" +
				"FFFFFBFRLR\n" +
				"FFBFFFBLRL\n" +
				"BBBFFFBLRR\n" +
				"FBBBBFFRLL\n" +
				"FFBFBBFLLL\n" +
				"BFFFFFFRLL\n" +
				"FFBBBFBRRL\n" +
				"FBFFBFBLRR\n" +
				"BFFBFBBLRR\n" +
				"BFFFBBFRRR\n" +
				"FBBFBBFLLL\n" +
				"BFBBFBBLRR\n" +
				"BBFBBFFLRL\n" +
				"FBBBFBBRLR\n" +
				"BFBBBFFRLR\n" +
				"FFFFFBBRRR\n" +
				"BBFFFBFLLR\n" +
				"BFFFFFBLLL\n" +
				"FBFBFFBRRR\n" +
				"BBFFBFBRLR\n" +
				"BFBBFBFLLR\n" +
				"FBFBFBFLLR\n" +
				"FBBBFFFRLL\n" +
				"BBFBFFBLRR\n" +
				"BBFBFFFRLR\n" +
				"BFBFFFBLRR\n" +
				"BFFBFFBRRL\n" +
				"FFFBFFBLLL\n" +
				"FFBFBFFRLL\n" +
				"BBFBFFBLLL\n" +
				"FBFFFFBRRR\n" +
				"BFBBBFBLLR\n" +
				"FBFBFFBRLL\n" +
				"BFBFBFBRRL\n" +
				"BFFBFFBLRL\n" +
				"FFBFFBFRLR\n" +
				"FBBBFFFLLL\n" +
				"FBFFFFFRRR\n" +
				"FFBFFFFLLR\n" +
				"FBBFFFFRRR\n" +
				"BFFFBFFRLR\n" +
				"BBBFFBBRLR\n" +
				"FFBFBFFLRL\n" +
				"FFFBFBBLLL\n" +
				"BBFBFBBRLR\n" +
				"FFFFFBBLRL\n" +
				"BFBFFBBLRL\n" +
				"FBBFFFFLLR\n" +
				"BBFBBFBLLL\n" +
				"BFFBBBBRRL\n" +
				"FBFFBBBRLR\n" +
				"BBBFBFFLLR\n" +
				"FFFFFBFRRR\n" +
				"FFFBBBBRLR\n" +
				"FFBBBFFLLL\n" +
				"FFFBBFFRRL\n" +
				"BFFFBFFLRR\n" +
				"FBBFFFBLRR\n" +
				"BFFBBFBRRL\n" +
				"FBFBBBFRLR\n" +
				"FBFFFBBRLR\n" +
				"FBFBFBBLLL\n" +
				"FFBFBBFLRL\n" +
				"FFBBBFFRLR\n" +
				"BBFBFBFRRL\n" +
				"FBBBFBBLRR\n" +
				"BFBBBFBLLL\n" +
				"FFFFBFBRLR\n" +
				"FFBBFFBRRL\n" +
				"FBFFBBBLRR\n" +
				"FFBFFFBLLL\n" +
				"FBBFFBFLLL\n" +
				"FFBBBFFRLL\n" +
				"FBFBFBFLLL\n" +
				"BBFFBFFRLR\n" +
				"BFFBFFFLLL\n" +
				"BBFBFBFRRR\n" +
				"FBFFFFFRLR\n" +
				"FBBFBFFRRR\n" +
				"BBFFFFFLLR\n" +
				"BFFFFBBLLL\n" +
				"FFBFBBBLRR\n" +
				"BFFBBBBLRL\n" +
				"BFBFBBBRRR\n" +
				"BFFBFBBRRR\n" +
				"FBBBFFBLLR\n" +
				"BBFBFFFRRL\n" +
				"FFFBBFBLLR\n" +
				"FBFBFFFLRL\n" +
				"FBFBBFBRLL\n" +
				"FFFBBBFRLR\n" +
				"BBFFBBBLLR\n" +
				"FBFBBFBRRR\n" +
				"BFBBFFBRLL\n" +
				"FBBFBFFRRL\n" +
				"FBFFFFFRRL\n" +
				"FFFFFBFLRR\n" +
				"FBBBFFFLLR\n" +
				"FBBBFFFRRL\n" +
				"BBFBFBBLRL\n" +
				"BFFFBFFLRL\n" +
				"FFFBBFFLLL\n" +
				"BBFFBBBRLL\n" +
				"FBFFBBFLLR\n" +
				"BFFBFFFRLL\n" +
				"FBFBBFFRRL\n" +
				"BFFBBFFRLR\n" +
				"FFFBBBFLLL\n" +
				"FBFFFFFLLR\n" +
				"BFBFBBFRRR\n" +
				"BFBBFFFLRR\n" +
				"FFBFBBFRLL\n" +
				"FBBFBFBLRL\n" +
				"FFFFBFFRRR\n" +
				"FFFBFBFLLR\n" +
				"FFBBFFFRRL\n" +
				"FBBFBBFLLR\n" +
				"BFBBBBBRRL\n" +
				"FFFFBFFRRL\n" +
				"FBFBBBBLLR\n" +
				"BBFBBBBLRL\n" +
				"BFBBBBFRRL\n" +
				"BBBFFBBLLR\n" +
				"BFFFBBBRLL\n" +
				"FBBBFBBLLR\n" +
				"FFFFBBBLRL\n" +
				"FBBFBFFLLR\n" +
				"FFBBBBFRRR\n" +
				"FFFFFBBLLL\n" +
				"FFFBFBBRLR\n" +
				"BFBBFBFRLL\n" +
				"FFFBBBFLRL\n" +
				"FBBFBFBRRL\n" +
				"FFFFBBFLRL\n" +
				"BFFBBBBRLL\n" +
				"FFFBFFBRRL\n" +
				"BFFFBBFRLR\n" +
				"FFFBFBBRRR\n" +
				"BFBBFBFLRL\n" +
				"BFBBBBBRLR\n" +
				"BBFBFBFLLR\n" +
				"FFFBBBFRRL\n" +
				"FBBFFBFRRL\n" +
				"FBBBBBBLRL\n" +
				"FFFBFBFLRR\n" +
				"BFFFBBFLLR\n" +
				"BFFBBBFRLL\n" +
				"BBFFBFBLRL\n" +
				"FFBBBBBLRR\n" +
				"FBFBFBFRRR\n" +
				"BFBBFFBLRL\n" +
				"BFFBBBFLLR\n" +
				"FFBFBBFLLR\n" +
				"BFFFBBFRLL\n" +
				"FFBFBFFLLR\n" +
				"FBBFBFFLRR\n" +
				"BFBBBFBRRR\n" +
				"BBBFFFBRRL\n" +
				"BFFFBFFRLL\n" +
				"FFBFBFFLLL\n" +
				"BBBFBFBRRL\n" +
				"FFFBFBBRRL\n" +
				"BFFBFFFRRR\n" +
				"BFFFBFFRRR\n" +
				"BFBFBFFLLR\n" +
				"BBFFFBBLRL\n" +
				"BFFFBFBLLR\n" +
				"BFBBBBBLLL\n" +
				"BFBFFFFRLR\n" +
				"FBFFFBBRRR\n" +
				"BBBFFBFRLL\n" +
				"FFFBBBFRRR\n" +
				"BFBFBFFRLR\n" +
				"FFBFBBBLLR\n" +
				"FBBFFBBRLL\n" +
				"BBBFFBBLRR\n" +
				"BBBFBFFRRR\n" +
				"FFFFBBFRRR\n" +
				"FBFFBBBRRR\n" +
				"BBBFFBFRLR\n" +
				"BBFBFFFLRR\n" +
				"FBFBFFFRRL\n" +
				"BBFBFBBLRR\n" +
				"FBBFBBBLLL\n" +
				"BFFFBFBLRR\n" +
				"FBBBBFFLLR\n" +
				"FBBBBFBLLR\n" +
				"FBBFFBBRRR\n" +
				"BBBFFFFRRL\n" +
				"BFFFBFBLLL\n" +
				"FBBBFBBRRR\n" +
				"FFBFBFBRLR\n" +
				"FFFFBBBRLL\n" +
				"BFBBBFBLRL\n" +
				"BBFBFFBLLR\n" +
				"FBFFBBBLLR\n" +
				"FFBBBFFRRR\n" +
				"FBBFBFBRLL\n" +
				"BBFFFFBLLR\n" +
				"FFBBFFFLRR\n" +
				"FBFFFBFLRR\n" +
				"BBBFFFFLRL\n" +
				"FFFFBFBLLR\n" +
				"FFFFFBFLLR\n" +
				"FFFFBFBLLL\n" +
				"FBFFBBFRLR\n" +
				"BBFFBBFLLR\n" +
				"FBFFFBBLRL\n" +
				"BBFBBFFLLR\n" +
				"BFBBFBBRLL\n" +
				"BFFFFFBRLR\n" +
				"FBBFBBFRRR\n" +
				"FFFBFBFRLL\n" +
				"BBFBBBBLLL\n" +
				"FFFFBFBLRR\n" +
				"BBBFFFBRLL\n" +
				"BBFFBFFLLR\n" +
				"FFBBBBBRRL\n" +
				"BFBFBBBLRL\n" +
				"FFBBBFBRLR\n" +
				"BFBFBBFRRL\n" +
				"FFBBBFBRRR\n" +
				"FFFBFBBRLL\n" +
				"BBFFBBBRRR\n" +
				"BFFBFBFLLL\n" +
				"BFFBBFBLRL\n" +
				"BFBFFFFLLR\n" +
				"FFBBFFBRLL\n" +
				"BBFBFFBRLL\n" +
				"BBFBFBBLLL\n" +
				"FBFBBBBLLL\n" +
				"FBFBBBFRRL\n" +
				"BFBFFFBLLR\n" +
				"BBFFBBBLLL\n" +
				"FBFFBFBRLL\n" +
				"BFBBFBBRLR\n" +
				"FFFBFFBRRR\n" +
				"BBFBFBBRRR\n" +
				"FBFFBBFRRR\n" +
				"FFBFFBFRLL\n" +
				"FBBFFBFLRR\n" +
				"BBBFBFBLRR\n" +
				"BBBFFBFRRR\n" +
				"FBBFBFBLLL\n" +
				"BFFFFBBLRR\n" +
				"FBFBFBFRLR\n" +
				"FBFBBFFRLR\n" +
				"FBFBFFBRRL\n" +
				"BFBBFFBRRR\n" +
				"FBFFBFBLLR\n" +
				"BFBFBFBLLL\n" +
				"BBFFFFFRRR\n" +
				"FBFBFFBLRL\n" +
				"BBFFBBFLLL\n" +
				"BFBFFFFLLL\n" +
				"FFBFBBFRLR\n" +
				"BBFFBFFLLL\n" +
				"BFBBFBBLLR\n" +
				"FFFFFBFRLL\n" +
				"BBFBBFFRRR\n" +
				"BFFFBBBRRL\n" +
				"BBFBBFFLLL\n" +
				"FBBFFBFLLR\n" +
				"FFBBBFBLRR\n" +
				"BFBFBFBRLR\n" +
				"BBBFFFBRRR\n" +
				"FBBFFBBLRR\n" +
				"FFBBBFFLLR\n" +
				"BFFFFBFLLL\n" +
				"BFBFFBFLLL\n" +
				"BBFBFFFLLL\n" +
				"FBFBFFBLLL\n" +
				"BBFFBFBRRL\n" +
				"BBFBBFBLRL\n" +
				"FBFBFFBLLR\n" +
				"BBFFBFBLRR\n" +
				"FBFFBBBRRL\n" +
				"FFBFFBFRRR\n" +
				"BBFBBBFLLL\n" +
				"BFBFBBBRLL";

	}
}
